# Generated by Django 4.0.6 on 2023-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Romance novel', 'Romance novel'), ('Autobiography', 'Autobiography'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Memoir', 'Memoir'), ('Horror', 'Horror'), ('Philosophy', 'Philosophy'), ('CookBook', 'CookBook'), ("Children's literature", "Children's literature"), ('Anthology', 'Anthology'), ('Nonfiction', 'Nonfiction'), ('Short story', 'Short story'), ('Crime', 'Crime'), ('Encyclopedia', 'Encyclopedia'), ('Dairy', 'Dairy'), ('Politics', 'Politics'), ('Biblophile', 'Biblophile'), ('Fable', 'Fable'), ('Fiction', 'Fiction')], default='hai', max_length=30, verbose_name='UserType'),
            preserve_default=False,
        ),
    ]
