# Generated by Django 4.0.6 on 2023-04-29 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_bookfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookfile',
            field=models.FileField(upload_to='audio', verbose_name='Review File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookimg',
            field=models.ImageField(upload_to='fileimages', verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='createdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Create DateTime'),
        ),
    ]
