# Generated by Django 4.0.6 on 2023-04-29 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_bookfile_alter_book_bookimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='createdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create DateTime'),
        ),
    ]
