# Generated by Django 4.0.6 on 2023-04-29 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_createdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified_Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='modifieddatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_login'),
        ),
    ]
