# Generated by Django 4.0.6 on 2023-05-17 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_user_date_joined_alter_user_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktype',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('romance novel', 'romance novel'), ('autobiography', 'autobiography'), ('biography', 'biography'), ('mystery', 'mystery'), ('memoir', 'memoir'), ('horror', 'horror'), ('philosophy', 'philosophy'), ('cookbook', 'cookbook'), ("children's literature", "children's literature"), ('anthology', 'anthology'), ('nonfiction', 'nonfiction'), ('short story', 'short story'), ('drime', 'drime'), ('dncyclopedia', 'dncyclopedia'), ('dairy', 'dairy'), ('politics', 'politics'), ('biblophile', 'biblophile'), ('fable', 'fable'), ('fiction', 'fiction')], max_length=30, verbose_name='BookType'),
        ),
        migrations.AlterField(
            model_name='book',
            name='createdatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create DateTime'),
        ),
        migrations.AlterField(
            model_name='book',
            name='modifieddatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified DateTime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_login'),
        ),
    ]
